import Head from 'next/head';
import Header from '../components/Header/Header';
import Footer from '../components/Footer/Footer';
import Link from 'next/link';

import contactList from '../components/Contacts/contact-list';

export default function projects() {
  return (
    <>
      <Head>
        <title>Contacts | Adif</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex flex-col relative bg-slate-900 min-w-screen h-screen">
        <div className="flex">
          <Header />
        </div>
        <div className="relative flex-auto max-w-xl md:max-w-5xl mx-auto w-full max-h-3/4 h-full">
          <div className="flex flex-col justify-center h-full">
            <div className="flex flex-col bg-slate-300 rounded-xl w-3/4 py-10 px-5 md:p-20 mx-auto border-4 border-indigo-600">
              <h1 className="text-center font-bold text-5xl text-indigo-900 mb-5">
                Get in touch!
              </h1>
              <p className="text-center font-semibold text-xl text-slate-500 mb-10">
                Contact me if you have any further quesion
              </p>
              <div className="flex flex-col max-w-sm mx-auto w-full">
                {contactList.map((contact, key) => {
                  return (
                    <Link href={contact.link} key={key}>
                      <a target="_blank" rel="noopener noreferrer">
                        <div className="flex flex-row px-5 py-2 rounded-xl hover:bg-slate-50 hover:drop-shadow-lg transition ease-in-out mb-2">
                          {contact.icon}
                          <p className="flex-auto font-semibold text-xl my-auto">
                            {contact.alias}
                          </p>
                        </div>
                      </a>
                    </Link>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
        <div className="flex">
          <Footer />
        </div>
      </main>
    </>
  );
}
