import Head from 'next/head';
import Header from '../components/Header/Header';

export default function Home() {
  return (
    <div className="font-main">
      <Head>
        <title>Homepage | Adif</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative bg-slate-900 w-screen h-screen">
        <Header />
      </main>
    </div>
  );
}
