import Head from 'next/head';
import Header from '../components/Header/Header';
import HomeCard from '../components/Home/HomeCard';
import content from '../components/Home/content-card';
import Link from 'next/link';
import path from '../components/path';
import Footer from '../components/Footer/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Homepage | Adif</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex flex-col relative bg-slate-900 min-w-screen h-screen">
        <div className="flex">
          <Header />
        </div>
        <div className="flex-1 max-w-7xl mx-auto w-full">
          <div className="flex items-center h-full">
            <div className="flex flex-col md:flex-row justify-around w-full">
              <Link href={path.profile} className="flex justify-center">
                <a>
                  <HomeCard content={content.profile} />
                </a>
              </Link>
              <Link href={path.projects} className="flex justify-center">
                <a>
                  <HomeCard content={content.projects} />
                </a>
              </Link>
              <Link href={path.contact} className="flex justify-center">
                <a>
                  <HomeCard content={content.contact} />
                </a>
              </Link>
            </div>
          </div>
        </div>
        <div className="flex">
          <Footer />
        </div>
      </main>
    </div>
  );
}
