import React from 'react';
import Head from 'next/head';
import Header from '../components/Header/Header';
import Footer from '../components/Footer/Footer';
import Introduction from '../components/Profile/Introduction';
import Skills from '../components/Profile/Skills';
export default function profile() {
  return (
    <>
      <Head>
        <title>Profile | Adif</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex flex-col relative min-w-screen min-h-screen h-full">
        <div className="flex bg-slate-900">
          <Header />
        </div>
        <div className="flex bg-slate-50">
          <div className="max-w-7xl mx-auto w-full p-16">
            <Introduction />
          </div>
        </div>
        <div className="flex-auto">
          <div className="max-w-7xl mx-auto w-full p-16">
            <Skills />
          </div>
        </div>
        <div className="flex">
          <Footer />
        </div>
      </div>
    </>
  );
}
