import React from 'react';
import Head from 'next/head';
import Header from '../components/Header/Header';
import Footer from '../components/Footer/Footer';

import { UserCircleIcon } from '@heroicons/react/outline';
export default function profile() {
  return (
    <>
      <Head>
        <title>Profile | Adif</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex flex-col relative bg-slate-900 w-screen h-screen">
        <div className="flex">
          <Header />
        </div>
        <div className="flex-1 bg-slate-300 px-20 pt-10 pb-5">
          <div className="flex flex-row h-full">
            <div className="flex-1 flex-col m-10 bg-slate-200 rounded-3xl">
              <div>
                <div className="flex-1 p-5">
                  <div className="flex justify-center pt-5 pb-10">
                    <div className="flex flex-row">
                      <UserCircleIcon className="flex h-10 w-10 text-slate-900" />
                      <h1 className="font-bold text-center text-4xl mx-3">
                        PROFILE
                      </h1>
                    </div>
                  </div>
                </div>
              </div>
              <div className="flex-none p-5">Skills</div>
            </div>
            <div className="flex-1 flex-col m-10 bg-slate-200 rounded-3xl">
              Workshops
            </div>
          </div>
        </div>
        <div className="flex">
          <Footer />
        </div>
      </div>
    </>
  );
}
