import React from 'react';
import Head from 'next/head';
import Header from '../components/Header/Header';
export default function profile() {
  return (
    <>
      <Head>
        <title>Profile | Adif</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="bg-slate-900">
        <Header />
      </div>
    </>
  );
}
