import React from 'react';
import Head from 'next/head';
import Header from '../components/Header/Header';
import { API_URL } from '../config/index';
import Projects from '../components/Projects/Projects';
import Footer from '../components/Footer/Footer';
import Link from 'next/link';
import path from '../components/path';

export default function projects({ projects }) {
  return (
    <>
      <Head>
        <title>Projects | Adif</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex flex-col relative min-w-screen min-h-screen h-full">
        <div className="flex bg-slate-900">
          <Header />
        </div>
        <div className="flex-auto bg-slate-200">
          <div className="max-w-7xl mx-auto w-full py-16 px-5">
            {projects === null ? (
              <div className="text-center font-semibold ">
                <h2 className="text-slate-700 text-3xl mb-5">
                  No projects to show
                </h2>
                <p className="text-slate-400 text-xl">
                  Return to{' '}
                  <Link href={path.home}>
                    <a className="text-indigo-500">home</a>
                  </Link>
                </p>
              </div>
            ) : (
              <Projects projects={projects} />
            )}
          </div>
        </div>
        <div className="flex">
          <Footer />
        </div>
      </div>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch(`${API_URL}/api/projects?populate=*`);
  const projects = await res.json();

  return {
    props: { projects: projects.data },
  };
}
